### PR TITLE
Use per-function lodash modules

### PR DESCRIPTION
**Pull request by ArnaudRinquin**
Get rid two third of the lib size:

From:

```
dist
├── [426K]  fetch-factory.js
└── [121K]  fetch-factory.min.js
```

To:

```
dist
├── [107K]  fetch-factory.js
└── [ 44K]  fetch-factory.min.js
```

### CODE REVIEW

**Comment by jackfranklin** [comment]
Ah I think merging some of the other PRs has caused the conflict :( Would you mind rebasing? This is great work though, thank you!

That bundle still seems really large, be great to play with getting it down in size, but you've saved about 60% on the minified one so that's well worth it!

**Comment by ArnaudRinquin** [comment]
Done

**Comment by jackfranklin** [comment]
This is awesome, thank you!

**Comment by jdalton** [comment]
You can also cherry-pick them from the `lodash` package too:

``` js
var assign = require('lodash/object/assign');
```

**Pull request merged**
