### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by copyhold**
handle port in url

### CODE REVIEW

**Comment by jackfranklin** [comment]
Thanks! Do you fancy writing a test to cover this? The existing tests should guide you most of the way but I'm happy to answer Qs :)

**Comment by copyhold** [comment]
upph...
This gonna be my first JS test

I'll try

**Comment by jackfranklin** [comment]
:) else I'm happy to / I'm happy to help too!

**Comment by copyhold** [comment]
Ok, test added

**Comment by jackfranklin** [comment]
Thank you! With the changes in 0.2.0 this now needs rebasing but I'll do it shortly :)

**Comment by jackfranklin** [comment]
@copyhold thanks for your work on this, I reworked this to fit the new structure https://github.com/jackfranklin/fetch-factory/commit/637e0462c9967467a2b4a4376a861dbcf020fae0. It's out in 0.2.1

**Pull request closed without merging**
